version: "3.9"

services:
  jenkins:
    image: tushar27799/jenkins:custom
    container_name: jenkins-corextech
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
    external: true   # 👈 if you want to reuse your existing volume (ws_jenkins-data)
    name: ws_jenkins-data

