services:
  website:
    build: .
    container_name: website
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    networks:
      - webnet
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d  # init script
    networks:
      - webnet

volumes:
  mysql_data:

networks:
  webnet:
    driver: bridge
